# Generated by Django 4.0.5 on 2022-06-02 16:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(default='', verbose_name='Описание')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('importance', models.BooleanField(default=True, verbose_name='Важность')),
                ('condition', models.IntegerField(choices=[(1, 'Активно'), (2, 'Отложено'), (3, 'Выполнено')], default=1, verbose_name='Состояние')),
                ('date_and_time', models.DateTimeField(default=datetime.datetime(2022, 6, 3, 19, 22, 38, 777350), verbose_name='Время создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'записи',
            },
        ),
    ]
